#
# HomePlay Lite OS pacman.conf for archiso builds
#

[options]
HoldPkg     = pacman glibc
Architecture = auto
ParallelDownloads = 5
Color
CheckSpace
VerbosePkgLists
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
